version: '3.3'
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - name=value
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=8520
      - POSTGRES_DB=simple_bank
  api:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - '8080:8080'
    environment:
      - DSN=postgresql://root:8520@postgres:5432/simple_bank?sslmode=disable
