// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: verify_email.sql

package db

import (
	"context"
)

const createVerifyEmail = `-- name: CreateVerifyEmail :one
INSERT INTO verify_emails (
  secret_code,  
  username, 
  email 
) VALUES (
    $1, $2, $3
) RETURNING id, secret_code, username, email, is_used, created_at, expires_at
`

type CreateVerifyEmailParams struct {
	SecretCode string `json:"secret_code"`
	Username   string `json:"username"`
	Email      string `json:"email"`
}

func (q *Queries) CreateVerifyEmail(ctx context.Context, arg CreateVerifyEmailParams) (VerifyEmail, error) {
	row := q.db.QueryRowContext(ctx, createVerifyEmail, arg.SecretCode, arg.Username, arg.Email)
	var i VerifyEmail
	err := row.Scan(
		&i.ID,
		&i.SecretCode,
		&i.Username,
		&i.Email,
		&i.IsUsed,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
