# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: 8520
          POSTGRES_DB: simple_bank
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '^1.21'
    
    - name: Install golang-migrate
      run: |
        wget http://github.com/golang-migrate/migrate/releases/latest/download/migrate.linux-amd64.deb && sudo dpkg -i migrate.linux-amd64.deb
        rm migrate.linux-amd64.deb
        which migrate

    - name: Wait for PostgreSQL to start
      run: sleep 5

    - name: Clean previous data
      run: make dropdb

    - name: Rebuild DB
      run: make createdb

    - name: Run migrations
      run: make migrateup

    - name: Test
      run: make test
